### ISSUE TITLE
Steam wishlist not syncing anymore

### ISSUE THREAD

**Issue by romainrichard** [micso/easy-steamgifts#1]
A few weeks ago, I noticed that some giveaways were not being highlighted on SteamGifts even though there were in my wishlist on Steam, so I went into the options of Easy SteamGifts and clicked on the Wishlist link to refresh the list.
That didn't do anything, I tried a few more times but to no avail. So I tried clearing up the wishlist and trying to syn up again, but that didn't work either.
So now Easy SteamGifts has an empty wishlist and I can't get it to sync.

Any suggestions?

**Comment by bmxmiso** [comment]
Hi @romainrichard 

Thank you for reporting this issue. I just tried to sync my wishlist too and I noticed the same problem so I will try to prepare a fix soon.

**Comment by micso** [comment]
Hi @romainrichard

Thank you for reporting this issue. I just tried to sync my wishlist too and I noticed the same problem so I will try to prepare a fix soon.

**Comment by micso** [comment]
@romainrichard give me a link to your steamwishlist

**Comment by romainrichard** [comment]
[https://steamcommunity.com/id/rr00mm11/wishlist](https://steamcommunity.com/id/rr00mm11/wishlist)

**Comment by micso** [comment]
Thanks, problem should be fixed in version 2.5.1

**Comment by romainrichard** [comment]
Problem solved, thanks for fixing it!
