### ISSUE TITLE
Unpredictable work on Wishlist and Recommended pages

### ISSUE THREAD

**Issue by qarkai** [micso/easy-steamgifts#5]
Sometimes there is no quick join button and win chance label and eSG button on following pages:
https://www.steamgifts.com/giveaways/search?type=wishlist
https://www.steamgifts.com/giveaways/search?type=recommended

**Comment by micso** [comment]
Thank you for reporting this. I will prepare a fix asap ;).

**Comment by micso** [comment]
Fixed in version 2.6.2

**Comment by qarkai** [comment]
Cool! Thanks!
